export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';

export const ADD_TO_PRODUCT_REQUEST = 'ADD_TO_PRODUCT_REQUEST';

export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';

export const DELETE_PRODUCTS_REQUEST = 'DELETE_PRODUCTS_REQUEST';

export const ITEM_EDITTING = 'ITEM_EDITTING'; 

export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
